filter:
    excluded_paths:
        - vendor/*
        - test/jobs/*
    paths:
        - src/*
        - test/*

checks:
    php:
        code_rating: true
        duplication: true

tools:
    php_analyzer: true
    sensiolabs_security_checker: true
    external_code_coverage:
        timeout: 1200
        runs: 3