language: php

services:
    - redis-server

php:
    - 5.6
    - 5.5
    - 5.4

install:
    - composer install

before_script: 
    - phpenv config-add travis-php.ini
    - if [[ "$(phpenv version-name)" == "5.4" ]]; then pecl install proctitle; fi

script: ./vendor/bin/phing test